name: MDAKitRegistry-docs
channels:
    - conda-forge
    - defaults
dependencies:
    # Base depends
    - python
    - pip

    - sphinx==5.3.0
    - mdanalysis-sphinx-theme

    - pyyaml
    - pydantic
    - requests
    - setuptools
    - packaging

    # Pip-only installs
    - pip:
      - PyGithub
