name: MDAKitRegistry-docs
channels:
    - conda-forge
    - defaults
dependencies:
    # Base depends
    - python
    - pip

    - sphinx
    - mdanalysis-sphinx-theme
    - sphinxcontrib-youtube

    - pyyaml
    - pydantic
    - requests
    - setuptools
    - packaging

    # Pip-only installs
    - pip:
      - PyGithub
