name: MDAKitRegistry-docs
channels:
dependencies:
    # Base depends
    - python
    - pip

    - sphinx
    - sphinx_rtd_theme

    - pyyaml
    - pydantic
    - requests
    - setuptools
    - packaging

    # Pip-only installs
    - pip:
      - PyGithub
