name: MDAKitRegistry-docs
channels:
    - conda-forge
    - defaults
dependencies:
    # Base depends
    - python
    - pip

    - sphinx
    - mdanalysis-sphinx-theme

    - pyyaml
    - pydantic
    - requests
    - setuptools
    - packaging

    # Pip-only installs
    - pip:
      - PyGithub
      - git+https://github.com/MDAnalysis/mdanalysis-sphinx-theme.git@update-theme

